# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi

import rclpy
from rclpy.node import Node
from std_msgs.msg import String
import epos_action_node.action as ep


os.environ['LD_LIBRARY_PATH'] = ''

class ExePublisher(Node):
    def __init__(self):
        super().__init__("exe_sub")
        self.publisher = self.create_publisher(String, 'exerciseAvail', 10)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(610, 568)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_6 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_2.addWidget(self.radioButton_6)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.radioButton_5 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.radioButton_7 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_2.addWidget(self.radioButton_7)
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_2.addWidget(self.textEdit_3)
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_2.addWidget(self.textEdit_4)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.textEdit_5 = QtWidgets.QTextEdit(Form)
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_2.addWidget(self.textEdit_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.buttonBox.accepted.connect(self.handle_accepted)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Selected an exercise : "))
        self.radioButton.setText(_translate("Form", "Homing"))
        self.radioButton_3.setText(_translate("Form", "Back to position 0"))
        self.radioButton_6.setText(_translate("Form", "Concentric flexion"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Hip :   </span>from 20° extension to 20° flexion   |   <span style=\" font-style:italic;\">speed = 10 dps</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Knee :   </span>from 40° to 0°    |    <span style=\" font-style:italic;\">speed = 10 dps</span></p></body></html>"))
        self.radioButton_5.setText(_translate("Form", "Concentric flexion"))
        self.textEdit_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Hip :</span>   from 10° flexion to 30° flexion    |    <span style=\" font-style:italic;\">speed = 10 dps</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Knee :</span>   from 40° to 0°    |    <span style=\" font-style:italic;\">speed = 10 dps</span></p></body></html>"))
        self.radioButton_7.setText(_translate("Form", "Eccentric flexion"))
        self.textEdit_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Hip :</span>   from 10° flexion to 10° extension    |    <span style=\" font-style:italic;\">speed = 5 dps</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Knee : </span>  from 50° to 70°    |    <span style=\" font-style:italic;\">speed = 5 dps</span></p></body></html>"))
        self.radioButton_4.setText(_translate("Form", "Eccentric flexion"))
        self.textEdit_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Hip : </span>  from 60° flexion to 20° extension    |    <span style=\" font-style:italic;\">speed = 10 dps</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Knee : </span>  from 0° to 80°    |    <span style=\" font-style:italic;\">speed = 10 dps</span></p></body></html>"))
        self.radioButton_2.setText(_translate("Form", "Knee up"))
        self.textEdit_5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Hip : </span>  from 0° to 65° flexion    |    <span style=\" font-style:italic;\">speed = 20 dps</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Knee : </span>  from 0° to 65°    |    <span style=\" font-style:italic;\">speed = 20 dps</span> </p></body></html>"))


    def handle_accepted(self):
        self.publish_message()
        


    def publish_message(self):
        msg = String()
        if self.radioButton.isChecked():
            msg.data = '{"loop":1,"commands":[{"type":"homing","distance":"0"}]}'
            print('Homing')
        elif self.radioButton_3.isChecked():
            msg.data = '{"loop":1,"commands":[{"type":"pos","motor0":{"value":"-27","dps":"8"}, "motor1":{"value":"0","dps":"8"}}]}'
            print('Back to position 0')
        elif self.radioButton_6.isChecked():  
            msg.data = '{"loop":3,"commands":[{"type":"pos","motor0":{"value":"-7","dps":"10"}, "motor1":{"value":"40","dps":"10"}},{"type":"pos","motor0":{"value":"-47","dps":"10"}, "motor1":{"value":"0","dps":"10"}}]}'
            print('1 Concentric flexion')
        elif self.radioButton_5.isChecked(): 
            msg.data = '{"loop":3,"commands":[{"type":"pos","motor0":{"value":"-37","dps":"10"}, "motor1":{"value":"40","dps":"10"}},{"type":"pos","motor0":{"value":"-57","dps":"10"}, "motor1":{"value":"0","dps":"10"}}]}'
            print('2 Concentric flexion')
        elif self.radioButton_7.isChecked():
            msg.data = '{"loop":6,"commands":[{"type":"pos","motor0":{"value":"-37","dps":"5"}, "motor1":{"value":"50","dps":"5"}},{"type":"pos","motor0":{"value":"-17","dps":"5"}, "motor1":{"value":"70","dps":"5"}}]}'
            print('1 Eccentric flexion')
        elif self.radioButton_4.isChecked():
            msg.data = '{"loop":3,"commands":[{"type":"pos","motor0":{"value":"-87","dps":"10"}, "motor1":{"value":"0","dps":"10"}},{"type":"pos","motor0":{"value":"-7","dps":"10"}, "motor1":{"value":"80","dps":"10"}}]}'
            print('2 Eccentric flexion')
        elif self.radioButton_2.isChecked():
            msg.data = '{"loop":3,"commands":[{"type":"pos","motor0":{"value":"-27","dps":"20"}, "motor1":{"value":"0","dps":"20"}},{"type":"pos","motor0":{"value":"-92","dps":"20"}, "motor1":{"value":"65","dps":"20"}}]}'
            print('Knee up')

        #self.publisher.publish(msg)

if __name__ == "__main__":
    # Set the QT_QPA_PLATFORM environment variable to "xcb"
    os.environ["QT_QPA_PLATFORM"] = "xcb"

    rclpy.init(args=sys.argv)

    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(window)

    publisher = ExePublisher()

    window.show()
    sys.exit(app.exec_())